### ISSUE TITLE
Regression with nested objects querying

### ISSUE THREAD

**Issue by oleduc** [ramses-tech/nefertari#129]
## Description:
It is no longer possible to objects using field that contain nested objects. We noticed this bug because our application used this feature extensively and now it doesn't work anymore since we updated to 0.6.

This used to work given that a user is populated accordingly:
http://localhost:6543/api/users?_limit=2&profile.address=Foo&status=active

Now it doesn't return anything.

## Steps to repoduce:
Create a user:
http://localhost:6543/api/users?_m=POST&username=test&email=such@test.com&password=test

Create a profile
http://localhost:6543/api/users/test/profile?_m=POST&address=Foo

Query:
http://localhost:6543/api/users?_limit=2&profile.address=Foo&status=active

## Suspected reason:
The field type has changed from "object" to "nested" and it might not be possible to query nested objects using the query_string syntax that nefertari is using.

**Comment by postatum** [comment]
Please give more details:
* Did you use Ramses?
* What engine did you use?

**Comment by oleduc** [comment]
@postatum I used the provided ramses-example using nefertari-sqla.
https://github.com/brandicted/nefertari-example

With the default requirements for python 3.4:
Paste==2.0.2
PasteDeploy==1.5.2
PyYAML==3.11
SQLAlchemy==1.0.9
SQLAlchemy-Utils==0.31.3
Tempita==0.5.2
WebOb==1.5.1
attrs==15.1.0
blinker==1.4
click==6.0
cryptacular==1.4.1
elasticsearch==2.1.0
inflection==0.3.1
jsonref==0.1
markdown2==2.3.0
mongoengine==0.9.0
nefertari==0.6.1
nefertari-mongodb==0.4.1
nefertari-sqla==0.4.1
pbkdf2==1.3
psycopg2==2.6.1
pymongo==2.8
pyramid==1.5.7
pyramid-sqlalchemy==1.4
pyramid-tm==0.12
python-dateutil==2.4.2
ramlfications==0.1.8
ramses==0.5.1
-e git+git@github.com:brandicted/ramses-example.git@bbc1af0f8dbd74487972124b35a5dc6d01498c20#egg=ramses_example-origin/HEAD
repoze.lru==0.6
requests==2.8.1
simplejson==3.8.1
six==1.10.0
termcolor==1.1.0
transaction==1.4.4
translationstring==1.3
urllib3==1.12
venusian==1.0
waitress==0.8.9
xmltodict==0.9.2
zope.deprecation==4.1.2
zope.dottedname==4.1.0
zope.interface==4.1.3
zope.sqlalchemy==0.7.6

**Comment by oleduc** [comment]
@postatum Turns out this bug originates from nefertari-sqla. I created a pull request fixing the issue.
https://github.com/brandicted/nefertari-sqla/pull/87
